function [kx,ky,ko,kv,kov,x,y,o,vel,tvel,t,dt] = kalman_plot(filename, posAngVelAngvelErr = 0)
  % parse data generated by gts to evaluate kalman performance

  dat = load(filename);

  % kalman state
  t   = dat(:,1); % timestamp [ms ]
  kx  = dat(:,2); % x         [pix]
  ky  = dat(:,3); % y         [pix]
  ko  = dat(:,4); % angle     [rad]
  kv  = dat(:,5); % vel       [pix/ms]
  kov = dat(:,6); % ang vel   [rad/ms]
  kerr= dat(:,7); % kalman error factor

  % klt values
  x   = dat(:,8);
  y   = dat(:,9);
  o   = dat(:,10);

  %% velocities
  dt  = t(2:end)-t(1:end-1);
  tvel= t(2:end);
  % calculate vel
  vel = [x(2:end) y(2:end)] - [x(1:end-1) y(1:end-1)];
  vel = sqrt(vel(:,1).^2 + vel(:,2).^2)./dt;
  % calculate angular vel
  ov  = o(2:end) - o(1:end-1);

  %% plots

  % angle
  figure
  subplot(3,1,1);
  hold on; grid on;
  plot(t,o,'*b','markersize', 3);
  plot(t,ko,'g');
  axis tight;
  hold off;
  ylabel('angle [rad]');
  xlabel('t(ms)');
  legend('ang','kang');
  endfunction

  subplot(3,1,2);
  hold on; grid on;
  plot(tvel,ov,'*b','markersize', 3);
  plot(t,kov,'g');
  axis tight;
  hold off;
  ylabel('angle [rad/s]');
  xlabel('t(ms)');
  legend('ang','kang');

  % kalman err
  subplot(3,1,3)
  plot(t,kerr,'r');
  grid on;
  axis tight;
  ylabel('error');
  legend('kerr');

  % position,velocity
  figure
  subplot(3,1,1)
  % vel
  hold on; grid on;
  plot(tvel, vel);
  plot(t,kv,'g');
  axis tight;
  hold off;
  title('velocity');
  xlabel('t(ms)');
  ylabel('px/ms');
  legend('vel', 'kvel');

  % position
  subplot(3,1,2)
  hold on; grid on;
  normX = x - min(x); normX = normX / max(normX);
  normY = y - min(y); normY = normY / max(normY);
  normKX = kx - min(kx); normKX = normKX / max(normKX);
  normKY = ky - min(ky); normKY = normKY / max(normKY);
  plot(t,normX,'*k', 'markersize', 3);
  plot(t,normKX,'b');
  plot(t,normY,'*r', 'markersize', 3);
  plot(t,normKY,'g');
  axis tight;
  hold off;
  ylabel('position (normalized)');
  xlabel('t(ms)');
  legend('x', 'kx','y','ky');

  % kalman err
  subplot(3,1,3)
  plot(t,kerr,'r');
  grid on;
  axis tight;
  ylabel('error');
  legend('kerr');

  out = [x  y  o  [vel(1);vel] [ov(1);ov] ];
  kout= [kx ky ko kv           kov];

  if ( posAngVelAngvelErr > 0 )
    tout = t;
    if ( posAngVelAngvelErr > 3 )
      tout = [tvel(1);tvel];
    endif
    figure(69);
    hold on; grid on;
    plot(tout,out(:,posAngVelAngvelErr),'*b','markersize',3);
    plot(tout,kout(:,posAngVelAngvelErr),'g');
    legend('klt','kalman');
    axis tight;
  endif

endfunction
